# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_NO_PARALLEL'] = 'yes'

Vagrant.configure(2) do |config|

  NodeCount = 1

  (1..NodeCount).each do |i|
    config.vm.define "ubuntuvm0#{i}" do |node|
      node.vm.box = "ubuntu/bionic64"
      node.vm.hostname = "odfs.classroom.com"
      node.vm.network "private_network", ip: "100.10.0.75"
      node.vm.provider "virtualbox" do |v|
        v.name = "elk"
        v.memory = 2048
        v.cpus = 1
      end
    end
  end

end
